name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'   # Se déclenche uniquement sur les tags
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: extract_tag
        run: |
          # Extrait le tag actuel
          TAG_NAME=${GITHUB_REF##*/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: Dockerfile
          tags: |
            nicolasalbert/gmail_forwarder:latest
            nicolasalbert/gmail_forwarder:${{ env.TAG_NAME }}
          cache-from: type=registry,ref=nicolasalbert/gmail_forwarder:cache
          cache-to: type=registry,ref=nicolasalbert/gmail_forwarder:cache,mode=max

          build-args: BUILDKIT_INLINE_CACHE=1
